// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 6fZSWkofPMXR1NLi1bFj7o
// Component: 1vc1_cwciPOg-4
import * as React from "react";

import { Link, GatsbyLinkProps as LinkProps } from "gatsby";

import * as p from "@plasmicapp/react-web";
import * as ph from "@plasmicapp/host";

import {
  hasVariant,
  classNames,
  wrapWithClassName,
  createPlasmicElementProxy,
  makeFragment,
  MultiChoiceArg,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  pick,
  omit,
  useTrigger,
  StrictProps,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";
import Button from "../../Button"; // plasmic-import: 7une6Ae6nQQ_5/component

import "@plasmicapp/react-web/lib/plasmic.css";

import * as plasmic_new_habistack_com_css from "../new_habistack_com/plasmic_new_habistack_com.module.css"; // plasmic-import: rcEGNgTfxT6W6gDjnxsJgN/projectcss
import * as plasmic_library_plasmic_color_type_css from "../library_plasmic_color_type/plasmic_library_plasmic_color_type.module.css"; // plasmic-import: seaQhLVS4bbjiGvJJrRwyL/projectcss
import * as plasmic_habistack_marketing_css from "../habistack_marketing/plasmic_habistack_marketing.module.css"; // plasmic-import: cEHjHBABazmDxgQhPGAjL/projectcss
import * as projectcss from "./plasmic_fathym_platform_marketing.module.css"; // plasmic-import: 6fZSWkofPMXR1NLi1bFj7o/projectcss
import * as sty from "./PlasmicTechnology.module.css"; // plasmic-import: 1vc1_cwciPOg-4/css

import ChecksvgIcon from "./icons/PlasmicIcon__Checksvg"; // plasmic-import: UoPjMarBjLAJl_/icon
import ArrowRightsvgIcon from "./icons/PlasmicIcon__ArrowRightsvg"; // plasmic-import: dgkW2n0oQvm_D7/icon
import microsoftTeamsImage22PngYtYl0CU7 from "./images/microsoftTeamsImage22Png.png"; // plasmic-import: Yt_Yl0cU7/picture
import microsoftTeamsImage21PngMu0X4VOUc from "./images/microsoftTeamsImage21Png.png"; // plasmic-import: MU0x4vOUc/picture
import multiDatapngZw3PcLeDLaK0Ny from "./images/multiDatapng.png"; // plasmic-import: ZW3PCLeDLaK0Ny/picture
import cloudNativepngTFElapKifpNsAp from "./images/cloudNativepng.png"; // plasmic-import: tFElapKifpNsAp/picture
import microsoftTeamsImage17PngJm0FX6Qhm from "./images/microsoftTeamsImage17Png.png"; // plasmic-import: JM0fX6qhm/picture
import microsoftTeamsImage23PngYJJaM68 from "./images/microsoftTeamsImage23Png.png"; // plasmic-import: yJJaM_68-/picture
import microsoftTeamsImage18PngHswEwApnZ from "./images/microsoftTeamsImage18Png.png"; // plasmic-import: hswEWApnZ/picture
import oursYourspngCaSf9VRyMoVwL2 from "./images/oursYourspng.png"; // plasmic-import: caSF9VRyMOVwL2/picture
import microsoftTeamsImage19PngLgPuGiAwa from "./images/microsoftTeamsImage19Png.png"; // plasmic-import: LGPuGiAWA/picture

export type PlasmicTechnology__VariantMembers = {};
export type PlasmicTechnology__VariantsArgs = {};
type VariantPropType = keyof PlasmicTechnology__VariantsArgs;
export const PlasmicTechnology__VariantProps = new Array<VariantPropType>();

export type PlasmicTechnology__ArgsType = {};
type ArgPropType = keyof PlasmicTechnology__ArgsType;
export const PlasmicTechnology__ArgProps = new Array<ArgPropType>();

export type PlasmicTechnology__OverridesType = {
  root?: p.Flex<"section">;
  h2?: p.Flex<"h2">;
};

export interface DefaultTechnologyProps {
  className?: string;
}

function PlasmicTechnology__RenderFunc(props: {
  variants: PlasmicTechnology__VariantsArgs;
  args: PlasmicTechnology__ArgsType;
  overrides: PlasmicTechnology__OverridesType;

  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const $ctx = ph.useDataEnv?.() || {};
  const args = React.useMemo(() => Object.assign({}, props.args), [props.args]);

  const $props = {
    ...args,
    ...variants
  };

  const currentUser = p.useCurrentUser?.() || {};

  return (
    <section
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(
        projectcss.all,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        projectcss.plasmic_tokens,
        plasmic_new_habistack_com_css.plasmic_tokens,
        plasmic_library_plasmic_color_type_css.plasmic_tokens,
        plasmic_habistack_marketing_css.plasmic_tokens,
        sty.root
      )}
    >
      <div className={classNames(projectcss.all, sty.column__hlPaw)}>
        <h2
          data-plasmic-name={"h2"}
          data-plasmic-override={overrides.h2}
          className={classNames(
            projectcss.all,
            projectcss.h2,
            projectcss.__wab_text,
            sty.h2
          )}
        >
          {
            "Deploying applications to an enterprise-ready Azure environment has never been easier. "
          }
        </h2>

        <div
          className={classNames(
            projectcss.all,
            projectcss.__wab_text,
            sty.text__tzrR6
          )}
        >
          <React.Fragment>
            <span
              className={"plasmic_default__all plasmic_default__span"}
              style={{ color: "#0091FF", fontWeight: 700 }}
            >
              {
                "Spend more time coding and testing than provisioning and deploying. "
              }
            </span>
            <React.Fragment>{"\n\n"}</React.Fragment>
            <span
              className={"plasmic_default__all plasmic_default__span"}
              style={{ fontWeight: 700 }}
            >
              {"Fathym gives you a best practice, cloud-native workflow for"}
            </span>
            <React.Fragment> </React.Fragment>
            <span
              className={"plasmic_default__all plasmic_default__span"}
              style={{ fontWeight: 700, color: "#0091FF" }}
            >
              {"rapid "}
            </span>
            <React.Fragment>{""}</React.Fragment>
            <span
              className={"plasmic_default__all plasmic_default__span"}
              style={{ color: "#0091FF", fontWeight: 700 }}
            >
              {"application"}
            </span>
            <React.Fragment>{""}</React.Fragment>
            <span
              className={"plasmic_default__all plasmic_default__span"}
              style={{ fontWeight: 700, color: "#0091FF" }}
            >
              {" development, testing and release"}
            </span>
            <React.Fragment>{". "}</React.Fragment>
          </React.Fragment>
        </div>

        <div className={classNames(projectcss.all, sty.columns__hRdrr)}>
          <div className={classNames(projectcss.all, sty.column__d9EmO)}>
            <p.PlasmicImg
              alt={""}
              className={classNames(sty.img__tNd2K)}
              displayHeight={"230px" as const}
              displayMaxHeight={"none" as const}
              displayMaxWidth={"100%" as const}
              displayMinHeight={"0" as const}
              displayMinWidth={"0" as const}
              displayWidth={"auto" as const}
              loading={"lazy" as const}
              src={{
                src: microsoftTeamsImage22PngYtYl0CU7,
                fullWidth: 3542,
                fullHeight: 1563,
                aspectRatio: undefined
              }}
            />

            <div className={classNames(projectcss.all, sty.columns__es2En)}>
              <div className={classNames(projectcss.all, sty.column__cg5VY)}>
                <h4
                  className={classNames(
                    projectcss.all,
                    projectcss.h4,
                    projectcss.__wab_text,
                    sty.h4__rvws9
                  )}
                >
                  {"Composable Application Development "}
                </h4>

                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__heBv5
                  )}
                >
                  {"Future-proof"}
                </div>

                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__mxsOg
                  )}
                >
                  {
                    "Develop composable applications with modular frontends and microservices for agile and scalable application delivery. "
                  }
                </div>

                {true ? (
                  <Button
                    className={classNames("__wab_instance", sty.button__rxoMv)}
                    color={"softBlue" as const}
                    endIcon={
                      <ArrowRightsvgIcon
                        className={classNames(projectcss.all, sty.svg__psTnl)}
                        role={"img"}
                      />
                    }
                    shape={"rounded" as const}
                    showEndIcon={true}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__x7S5Q
                      )}
                    >
                      {"READ MORE"}
                    </div>
                  </Button>
                ) : null}
              </div>
            </div>
          </div>

          <div className={classNames(projectcss.all, sty.column__ibAej)}>
            <p.PlasmicImg
              alt={""}
              className={classNames(sty.img__ousF)}
              displayHeight={"230px" as const}
              displayMaxHeight={"none" as const}
              displayMaxWidth={"100%" as const}
              displayMinHeight={"0" as const}
              displayMinWidth={"0" as const}
              displayWidth={"auto" as const}
              loading={"lazy" as const}
              src={{
                src: microsoftTeamsImage21PngMu0X4VOUc,
                fullWidth: 3542,
                fullHeight: 1563,
                aspectRatio: undefined
              }}
            />

            <div className={classNames(projectcss.all, sty.columns__qIxEy)}>
              <div className={classNames(projectcss.all, sty.column__nniHb)}>
                <h4
                  className={classNames(
                    projectcss.all,
                    projectcss.h4,
                    projectcss.__wab_text,
                    sty.h4__mEzqL
                  )}
                >
                  {"Built-In CI/CD "}
                </h4>

                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text___6RNm
                  )}
                >
                  {"Out-of-the-box"}
                </div>

                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__nh9XV
                  )}
                >
                  {
                    "Automated build pipelines and source controls for no-code, hassle-free deployments. "
                  }
                </div>

                {true ? (
                  <Button
                    className={classNames("__wab_instance", sty.button__jdwPn)}
                    color={"softBlue" as const}
                    endIcon={
                      <ArrowRightsvgIcon
                        className={classNames(projectcss.all, sty.svg__imgQh)}
                        role={"img"}
                      />
                    }
                    shape={"rounded" as const}
                    showEndIcon={true}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text___3SasP
                      )}
                    >
                      {"READ MORE"}
                    </div>
                  </Button>
                ) : null}
              </div>
            </div>
          </div>

          <div className={classNames(projectcss.all, sty.column__keUsP)}>
            <p.PlasmicImg
              alt={""}
              className={classNames(sty.img__wNtac)}
              displayHeight={"230px" as const}
              displayMaxHeight={"none" as const}
              displayMaxWidth={"100%" as const}
              displayMinHeight={"0" as const}
              displayMinWidth={"0" as const}
              displayWidth={"auto" as const}
              loading={"lazy" as const}
              src={{
                src: multiDatapngZw3PcLeDLaK0Ny,
                fullWidth: 850,
                fullHeight: 375,
                aspectRatio: undefined
              }}
            />

            <div className={classNames(projectcss.all, sty.columns__jZDt)}>
              <div className={classNames(projectcss.all, sty.column__ff8Ra)}>
                <h4
                  className={classNames(
                    projectcss.all,
                    projectcss.h4,
                    projectcss.__wab_text,
                    sty.h4___66TDd
                  )}
                >
                  {"Application Governance  "}
                </h4>

                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__arqQs
                  )}
                >
                  {"Easily version and spin off new apps"}
                </div>

                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__wTo1H
                  )}
                >
                  {
                    "Consolidated control panel for hosting and managing your application portfolio."
                  }
                </div>

                {true ? (
                  <Button
                    className={classNames("__wab_instance", sty.button__rwnAi)}
                    color={"softBlue" as const}
                    endIcon={
                      <ArrowRightsvgIcon
                        className={classNames(projectcss.all, sty.svg__qC5E)}
                        role={"img"}
                      />
                    }
                    shape={"rounded" as const}
                    showEndIcon={true}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text___6Zxre
                      )}
                    >
                      {"READ MORE"}
                    </div>
                  </Button>
                ) : null}
              </div>
            </div>
          </div>
        </div>

        <div className={classNames(projectcss.all, sty.columns__t5SGi)}>
          <div className={classNames(projectcss.all, sty.column__qrOkH)}>
            <p.PlasmicImg
              alt={""}
              className={classNames(sty.img___0VRyD)}
              displayHeight={"230px" as const}
              displayMaxHeight={"none" as const}
              displayMaxWidth={"100%" as const}
              displayMinHeight={"0" as const}
              displayMinWidth={"0" as const}
              displayWidth={"auto" as const}
              loading={"lazy" as const}
              src={{
                src: cloudNativepngTFElapKifpNsAp,
                fullWidth: 850,
                fullHeight: 375,
                aspectRatio: undefined
              }}
            />

            <div className={classNames(projectcss.all, sty.columns__k7Axg)}>
              <div className={classNames(projectcss.all, sty.column__rd7Zg)}>
                <h4
                  className={classNames(
                    projectcss.all,
                    projectcss.h4,
                    projectcss.__wab_text,
                    sty.h4__p7EV5
                  )}
                >
                  {"Best Practice Cloud Infrastructure "}
                </h4>

                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__wpmEb
                  )}
                >
                  {"Azure cloud"}
                </div>

                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__qz8Kt
                  )}
                >
                  {
                    "Automated, best practice, cost effective Azure cloud provisioning."
                  }
                </div>

                {true ? (
                  <Button
                    className={classNames("__wab_instance", sty.button__eRbuy)}
                    color={"softBlue" as const}
                    endIcon={
                      <ArrowRightsvgIcon
                        className={classNames(projectcss.all, sty.svg__kEeXs)}
                        role={"img"}
                      />
                    }
                    shape={"rounded" as const}
                    showEndIcon={true}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__yfi6M
                      )}
                    >
                      {"READ MORE"}
                    </div>
                  </Button>
                ) : null}
              </div>
            </div>
          </div>

          <div className={classNames(projectcss.all, sty.column__ud3Su)}>
            <p.PlasmicImg
              alt={""}
              className={classNames(sty.img__gEUe1)}
              displayHeight={"230px" as const}
              displayMaxHeight={"none" as const}
              displayMaxWidth={"100%" as const}
              displayMinHeight={"0" as const}
              displayMinWidth={"0" as const}
              displayWidth={"auto" as const}
              loading={"lazy" as const}
              src={{
                src: microsoftTeamsImage17PngJm0FX6Qhm,
                fullWidth: 3542,
                fullHeight: 1563,
                aspectRatio: undefined
              }}
            />

            <div className={classNames(projectcss.all, sty.columns__d487I)}>
              <div className={classNames(projectcss.all, sty.column__zk3V3)}>
                <h4
                  className={classNames(
                    projectcss.all,
                    projectcss.h4,
                    projectcss.__wab_text,
                    sty.h4__yCls4
                  )}
                >
                  {"Our Cloud or Yours "}
                </h4>

                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__hzPtg
                  )}
                >
                  {"SaaS or Licensed"}
                </div>

                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__sYu72
                  )}
                >
                  {
                    "Get started hassle-free in our SaaS cloud. Scale to a cloud hosted in your own Azure tenant for maximum control. "
                  }
                </div>

                {true ? (
                  <Button
                    className={classNames("__wab_instance", sty.button___9JLg)}
                    color={"softBlue" as const}
                    endIcon={
                      <ArrowRightsvgIcon
                        className={classNames(projectcss.all, sty.svg___7SoJz)}
                        role={"img"}
                      />
                    }
                    shape={"rounded" as const}
                    showEndIcon={true}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__orFas
                      )}
                    >
                      {"READ MORE"}
                    </div>
                  </Button>
                ) : null}
              </div>
            </div>
          </div>

          <div className={classNames(projectcss.all, sty.column___1PC5)}>
            <p.PlasmicImg
              alt={""}
              className={classNames(sty.img__bmsZ)}
              displayHeight={"230px" as const}
              displayMaxHeight={"none" as const}
              displayMaxWidth={"100%" as const}
              displayMinHeight={"0" as const}
              displayMinWidth={"0" as const}
              displayWidth={"auto" as const}
              loading={"lazy" as const}
              src={{
                src: microsoftTeamsImage23PngYJJaM68,
                fullWidth: 3542,
                fullHeight: 1563,
                aspectRatio: undefined
              }}
            />

            <div className={classNames(projectcss.all, sty.columns___0TPDi)}>
              <div className={classNames(projectcss.all, sty.column___8Pwnq)}>
                <h4
                  className={classNames(
                    projectcss.all,
                    projectcss.h4,
                    projectcss.__wab_text,
                    sty.h4__oEhkU
                  )}
                >
                  {"Identity Management "}
                </h4>

                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__dKqMw
                  )}
                >
                  {"Custom SSO"}
                </div>

                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__uv5Vi
                  )}
                >
                  {
                    "Authenticate users across your applications. Set up custom single sign-on (SSO)."
                  }
                </div>

                {true ? (
                  <Button
                    className={classNames("__wab_instance", sty.button__olWd7)}
                    color={"softBlue" as const}
                    endIcon={
                      <ArrowRightsvgIcon
                        className={classNames(projectcss.all, sty.svg__snF4Q)}
                        role={"img"}
                      />
                    }
                    shape={"rounded" as const}
                    showEndIcon={true}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text___7NuB
                      )}
                    >
                      {"READ MORE"}
                    </div>
                  </Button>
                ) : null}
              </div>
            </div>
          </div>
        </div>

        <div className={classNames(projectcss.all, sty.columns__sR95)}>
          <div className={classNames(projectcss.all, sty.column__mQfw)}>
            <p.PlasmicImg
              alt={""}
              className={classNames(sty.img__hiViy)}
              displayHeight={"230px" as const}
              displayMaxHeight={"none" as const}
              displayMaxWidth={"100%" as const}
              displayMinHeight={"0" as const}
              displayMinWidth={"0" as const}
              displayWidth={"auto" as const}
              loading={"lazy" as const}
              src={{
                src: microsoftTeamsImage18PngHswEwApnZ,
                fullWidth: 3542,
                fullHeight: 1563,
                aspectRatio: undefined
              }}
            />

            <div className={classNames(projectcss.all, sty.columns___4OLdA)}>
              <div className={classNames(projectcss.all, sty.column__sd2S)}>
                <h4
                  className={classNames(
                    projectcss.all,
                    projectcss.h4,
                    projectcss.__wab_text,
                    sty.h4___1CIzA
                  )}
                >
                  {"Continuous Test and Release "}
                </h4>

                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text___2V9Ba
                  )}
                >
                  {"Streamlined UI"}
                </div>

                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__ke9Sj
                  )}
                >
                  {
                    "Accelerate development cycles. Fathym enables non-developers to easily test updates and ship to production when ready. "
                  }
                </div>

                {true ? (
                  <Button
                    className={classNames("__wab_instance", sty.button__qFkm)}
                    color={"softBlue" as const}
                    endIcon={
                      <ArrowRightsvgIcon
                        className={classNames(projectcss.all, sty.svg__eA6He)}
                        role={"img"}
                      />
                    }
                    shape={"rounded" as const}
                    showEndIcon={true}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__h7GX
                      )}
                    >
                      {"READ MORE"}
                    </div>
                  </Button>
                ) : null}
              </div>
            </div>
          </div>

          <div className={classNames(projectcss.all, sty.column__f0PKk)}>
            <p.PlasmicImg
              alt={""}
              className={classNames(sty.img__cdx1)}
              displayHeight={"230px" as const}
              displayMaxHeight={"none" as const}
              displayMaxWidth={"100%" as const}
              displayMinHeight={"0" as const}
              displayMinWidth={"0" as const}
              displayWidth={"auto" as const}
              loading={"lazy" as const}
              src={{
                src: oursYourspngCaSf9VRyMoVwL2,
                fullWidth: 850,
                fullHeight: 375,
                aspectRatio: undefined
              }}
            />

            <div className={classNames(projectcss.all, sty.columns__hj525)}>
              <div className={classNames(projectcss.all, sty.column__vqsuO)}>
                <h4
                  className={classNames(
                    projectcss.all,
                    projectcss.h4,
                    projectcss.__wab_text,
                    sty.h4___4IvK
                  )}
                >
                  {"Enterprise-Ready Security "}
                </h4>

                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__rxMSh
                  )}
                >
                  {"Secure your IP"}
                </div>

                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text___2RRhp
                  )}
                >
                  {
                    "Take advantage of Azure’s advanced security features. Secure your data ownership and intellectual property in your own Azure tenant."
                  }
                </div>

                {true ? (
                  <Button
                    className={classNames("__wab_instance", sty.button__zSwA)}
                    color={"softBlue" as const}
                    endIcon={
                      <ArrowRightsvgIcon
                        className={classNames(projectcss.all, sty.svg__vNO9)}
                        role={"img"}
                      />
                    }
                    shape={"rounded" as const}
                    showEndIcon={true}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__m3Sg5
                      )}
                    >
                      {"READ MORE"}
                    </div>
                  </Button>
                ) : null}
              </div>
            </div>
          </div>

          <div className={classNames(projectcss.all, sty.column__jfuzg)}>
            <p.PlasmicImg
              alt={""}
              className={classNames(sty.img___4EVn)}
              displayHeight={"230px" as const}
              displayMaxHeight={"none" as const}
              displayMaxWidth={"100%" as const}
              displayMinHeight={"0" as const}
              displayMinWidth={"0" as const}
              displayWidth={"auto" as const}
              loading={"lazy" as const}
              src={{
                src: microsoftTeamsImage19PngLgPuGiAwa,
                fullWidth: 3542,
                fullHeight: 1563,
                aspectRatio: undefined
              }}
            />

            <div className={classNames(projectcss.all, sty.columns__ry7Pe)}>
              <div className={classNames(projectcss.all, sty.column__z2PPp)}>
                <h4
                  className={classNames(
                    projectcss.all,
                    projectcss.h4,
                    projectcss.__wab_text,
                    sty.h4__eMiZp
                  )}
                >
                  {"Custom Workflows "}
                </h4>

                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__gyLoR
                  )}
                >
                  {"Extensible"}
                </div>

                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__diWXo
                  )}
                >
                  {
                    "Fathym not only offers simplified workflows for releasing your applications to the cloud but gives you the ability to create your own custom workflows to accelerate your team. "
                  }
                </div>

                {true ? (
                  <Button
                    className={classNames("__wab_instance", sty.button__bTmGr)}
                    color={"softBlue" as const}
                    endIcon={
                      <ArrowRightsvgIcon
                        className={classNames(projectcss.all, sty.svg__usidq)}
                        role={"img"}
                      />
                    }
                    shape={"rounded" as const}
                    showEndIcon={true}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__gxd1J
                      )}
                    >
                      {"READ MORE"}
                    </div>
                  </Button>
                ) : null}
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root", "h2"],
  h2: ["h2"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  typeof PlasmicDescendants[T][number];
type NodeDefaultElementType = {
  root: "section";
  h2: "h2";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicTechnology__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicTechnology__VariantsArgs;
    args?: PlasmicTechnology__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicTechnology__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    // Specify args directly as props
    Omit<PlasmicTechnology__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: [...PlasmicDescendants[nodeName]],
          internalArgPropNames: PlasmicTechnology__ArgProps,
          internalVariantPropNames: PlasmicTechnology__VariantProps
        }),
      [props, nodeName]
    );

    return PlasmicTechnology__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicTechnology";
  } else {
    func.displayName = `PlasmicTechnology.${nodeName}`;
  }
  return func;
}

export const PlasmicTechnology = Object.assign(
  // Top-level PlasmicTechnology renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    h2: makeNodeComponent("h2"),

    // Metadata about props expected for PlasmicTechnology
    internalVariantProps: PlasmicTechnology__VariantProps,
    internalArgProps: PlasmicTechnology__ArgProps
  }
);

export default PlasmicTechnology;
/* prettier-ignore-end */
